"use client";

import { useState, useMemo, useEffect } from "react";
import StatusBadge from "./StatusBadge";
import LogStream from "./LogStream";
import TicketDetails from "./TicketDetails";
import WorkflowVisualization from "./WorkflowVisualization";
import CodeDiffViewer from "./CodeDiffViewer";
import FileExplorer from "./FileExplorer";
import CodeEditor from "./CodeEditor";
import { useAgentStream } from "@/lib/useAgentStream";
import { getMockTicket, updateTicketStatus } from "@/lib/mockTicketService";
import { getMockDiffForFile, getMockDiffsForChanges } from "@/lib/mockDiffService";
import { sampleFileStructure } from "@/lib/sampleData";
import type { FileOperation } from "@/types/agent-workflow";

type ViewMode = "diff" | "code";

interface CodeChangeDisplay {
  filePath: string;
  operation: FileOperation;
}

export default function AgentDashboard() {
  const [inputTicketId, setInputTicketId] = useState("");
  const [submittedTicketId, setSubmittedTicketId] = useState<string | null>(null);
  const [ticketDetails, setTicketDetails] = useState<ReturnType<typeof getMockTicket> | null>(null);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>("diff");

  const {
    phase,
    plan,
    codeChanges,
    prUrl,
    branchName,
    stagingUrl,
    prNumber,
    testResults,
    interrupted,
    interruptMessage,
    isRunning,
    logs,
    start: startAgentWorkflow,
    resume: resumeWorkflow,
  } = useAgentStream(submittedTicketId);

  // Update ticket status when agent starts
  useEffect(() => {
    if (submittedTicketId && phase !== "idle") {
      // Update ticket status based on agent phase
      let newStatus: "todo" | "in-progress" | "review" | "done" = "in-progress";
      if (phase === "done") {
        newStatus = "done";
      } else if (phase === "awaiting_approval") {
        newStatus = "review";
      }
      
      updateTicketStatus(submittedTicketId, newStatus);
      
      // Refresh ticket details
      const updatedTicket = getMockTicket(submittedTicketId);
      setTicketDetails(updatedTicket);
    }
  }, [phase, submittedTicketId]);

  // Generate mock diffs for the code changes
  const mockDiffs = useMemo(() => {
    if (codeChanges.length === 0) return {};
    return getMockDiffsForChanges(codeChanges as CodeChangeDisplay[]);
  }, [codeChanges]);

  // Get the diff for the selected file
  const selectedDiff = useMemo(() => {
    if (!selectedFile) return null;
    
    // Check if we have a diff for this file
    if (mockDiffs[selectedFile]) {
      return mockDiffs[selectedFile];
    }
    
    // If not, create a mock diff for it
    const matchingChange = codeChanges.find(change => change.filePath === selectedFile);
    if (matchingChange) {
      return getMockDiffForFile(selectedFile, matchingChange.operation as FileOperation);
    }
    
    return null;
  }, [selectedFile, mockDiffs, codeChanges]);

  // Generate mock file content for the selected file
  const selectedFileContent = useMemo(() => {
    if (!selectedFile) return "";
    
    const fileName = selectedFile.split("/").pop() || selectedFile;
    const extension = fileName.split(".").pop()?.toLowerCase() || "";
    
    // Generate mock content based on file type
    if (extension === "tsx" || extension === "ts") {
      return `// ${fileName}
// Generated by TEDU AI Agent

import React from "react";

interface ${fileName.split(".")[0]}Props {
  children?: React.ReactNode;
}

export function ${fileName.split(".")[0]}({ children }: ${fileName.split(".")[0]}Props) {
  return (
    <div className="${fileName.split(".")[0].toLowerCase()}">
      <h2>${fileName.split(".")[0]} Component</h2>
      <div className="content">
        {children}
      </div>
    </div>
  );
}

export default ${fileName.split(".")[0]};`;
    } else if (extension === "css") {
      return `/* ${fileName} */
/* Styles for ${fileName.split(".")[0]} component */

.${fileName.split(".")[0].toLowerCase()} {
  padding: 1rem;
  border-radius: 0.5rem;
  background-color: var(--background-secondary);
}

.${fileName.split(".")[0].toLowerCase()} h2 {
  font-size: 1.5rem;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 1rem;
}

.${fileName.split(".")[0].toLowerCase()} .content {
  color: var(--text-secondary);
  line-height: 1.6;
}`;
    } else if (extension === "json") {
      return `{
  "name": "${fileName.split(".")[0]}",
  "version": "1.0.0",
  "description": "Configuration for ${fileName.split(".")[0]}",
  "main": "index.js",
  "scripts": {
    "test": "echo \\"Error: no test specified\\" && exit 1"
  },
  "keywords": [],
  "author": "TEDU AI Agent",
  "license": "MIT"
}`;
    } else {
      return `# ${fileName}
# Created by TEDU AI Agent

This is the content of ${fileName}.

## Purpose
This file was ${selectedDiff?.operation === "create" ? "created" : selectedDiff?.operation === "modify" ? "modified" : "deleted"} 
as part of implementing ticket requirements.

## Details
- File: ${selectedFile}
- Operation: ${selectedDiff?.operation || "unknown"}
- Date: ${new Date().toISOString().split('T')[0]}`;
    }
  }, [selectedFile, selectedDiff]);

  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    const id = inputTicketId.trim();
    if (!id) return;
    
    const ticket = getMockTicket(id);
    setTicketDetails(ticket);
    setSubmittedTicketId(id);
    
    // Update ticket status to in-progress
    updateTicketStatus(id, "in-progress");
    
    setTimeout(startAgentWorkflow, 0);
  };

  const handleFileSelect = (filePath: string) => {
    setSelectedFile(filePath);
    // Default to diff view for modified files
    const matchingChange = codeChanges.find(change => change.filePath === filePath);
    setViewMode(matchingChange?.operation === "modify" ? "diff" : "code");
  };

  const handleResume = (approved: boolean) => {
    if (approved && submittedTicketId) {
      updateTicketStatus(submittedTicketId, "done");
      const updatedTicket = getMockTicket(submittedTicketId);
      setTicketDetails(updatedTicket);
    }
    resumeWorkflow(approved);
  };

  return (
    <div className="space-y-6">
      {/* ── Input Form ── */}
      <form
        onSubmit={handleSubmit}
        className="flex gap-3 items-center bg-gray-900 border border-gray-700 rounded-lg p-4"
      >
        <input
          type="text"
          placeholder="Jira Ticket ID (e.g. TEDU-42)"
          value={inputTicketId}
          onChange={(event) => setInputTicketId(event.target.value)}
          className="flex-1 bg-gray-800 border border-gray-600 rounded-md px-3 py-2 text-sm text-gray-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
          disabled={isRunning}
        />
        <button
          type="submit"
          disabled={isRunning || !inputTicketId.trim()}
          className="px-5 py-2 bg-blue-600 hover:bg-blue-500 disabled:bg-gray-700 disabled:text-gray-500 text-white text-sm font-semibold rounded-md transition-colors"
        >
          {isRunning ? "Running…" : "Run Agent"}
        </button>
      </form>

      {/* Main content grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left column: Ticket details and workflow */}
        <div className="lg:col-span-2 space-y-6">
          {/* ── Ticket Details ── */}
          {ticketDetails && (
            <TicketDetails ticket={ticketDetails} />
          )}

          {/* ── Workflow Visualization ── */}
          <WorkflowVisualization currentPhase={phase} />

          {/* ── Development Plan ── */}
          {plan.length > 0 && (
            <section className="bg-gray-900 border border-gray-700 rounded-lg p-4">
              <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">
                📋 Development Plan
              </h2>
              <ol className="space-y-1.5 list-decimal list-inside">
                {plan.map((task, index) => (
                  <li key={index} className="text-sm text-gray-200">
                    {task}
                  </li>
                ))}
              </ol>
            </section>
          )}

          {/* ── Code Changes ── */}
          {codeChanges.length > 0 && (
            <section className="bg-gray-900 border border-gray-700 rounded-lg p-4">
              <div className="flex items-center justify-between mb-3">
                <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                  💻 Code Changes ({codeChanges.length} files)
                </h2>
                <div className="flex items-center gap-2 text-xs text-gray-500">
                  <div className="flex items-center gap-1">
                    <div className="w-2 h-2 rounded-full bg-green-500"></div>
                    <span>Create</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <div className="w-2 h-2 rounded-full bg-yellow-500"></div>
                    <span>Modify</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <div className="w-2 h-2 rounded-full bg-red-500"></div>
                    <span>Delete</span>
                  </div>
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <h3 className="text-xs font-medium text-gray-500 uppercase">Created Files</h3>
                  <ul className="space-y-1">
                    {codeChanges
                      .filter(change => change.operation === "create")
                      .map((change, index) => (
                        <li 
                          key={index} 
                          className="flex items-center gap-2 text-sm font-mono cursor-pointer hover:bg-gray-800 p-2 rounded"
                          onClick={() => handleFileSelect(change.filePath)}
                        >
                          <span className="w-2 h-2 rounded-full bg-green-500"></span>
                          <span className="text-gray-300 truncate">{change.filePath}</span>
                        </li>
                      ))}
                    {codeChanges.filter(change => change.operation === "create").length === 0 && (
                      <li className="text-sm text-gray-500 italic p-2">No files created</li>
                    )}
                  </ul>
                </div>
                <div className="space-y-2">
                  <h3 className="text-xs font-medium text-gray-500 uppercase">Modified Files</h3>
                  <ul className="space-y-1">
                    {codeChanges
                      .filter(change => change.operation === "modify")
                      .map((change, index) => (
                        <li 
                          key={index} 
                          className="flex items-center gap-2 text-sm font-mono cursor-pointer hover:bg-gray-800 p-2 rounded"
                          onClick={() => handleFileSelect(change.filePath)}
                        >
                          <span className="w-2 h-2 rounded-full bg-yellow-500"></span>
                          <span className="text-gray-300 truncate">{change.filePath}</span>
                        </li>
                      ))}
                    {codeChanges.filter(change => change.operation === "modify").length === 0 && (
                      <li className="text-sm text-gray-500 italic p-2">No files modified</li>
                    )}
                  </ul>
                </div>
              </div>
              {codeChanges.filter(change => change.operation === "delete").length > 0 && (
                <div className="mt-4 pt-4 border-t border-gray-800">
                  <h3 className="text-xs font-medium text-gray-500 uppercase mb-2">Deleted Files</h3>
                  <ul className="space-y-1">
                    {codeChanges
                      .filter(change => change.operation === "delete")
                      .map((change, index) => (
                        <li 
                          key={index} 
                          className="flex items-center gap-2 text-sm font-mono cursor-pointer hover:bg-gray-800 p-2 rounded"
                          onClick={() => handleFileSelect(change.filePath)}
                        >
                          <span className="w-2 h-2 rounded-full bg-red-500"></span>
                          <span className="text-gray-300 truncate">{change.filePath}</span>
                        </li>
                      ))}
                  </ul>
                </div>
              )}
            </section>
          )}
        </div>

        {/* Right column: Status, test results, and logs */}
        <div className="space-y-6">
          {/* ── Status Bar ── */}
          <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
            <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">
              🚦 Current Status
            </h2>
            <div className="flex flex-col gap-3">
              <div className="flex items-center gap-3">
                <StatusBadge phase={phase} />
                {branchName && (
                  <span className="text-xs bg-gray-800 text-gray-300 px-2 py-1 rounded font-mono">
                    branch: {branchName}
                  </span>
                )}
              </div>
              {prUrl && (
                <a
                  href={prUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-blue-400 hover:underline inline-flex items-center gap-1"
                >
                  <span>Open PR ↗</span>
                  {prNumber && (
                    <span className="text-xs text-gray-400">#{prNumber}</span>
                  )}
                </a>
              )}
              {stagingUrl && (
                <a
                  href={stagingUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-teal-400 hover:underline inline-flex items-center gap-1"
                >
                  <span>View Staging ↗</span>
                </a>
              )}
            </div>
          </div>

          {/* ── Test Results ── */}
          {testResults && (
            <section
              className={`border rounded-lg p-4 ${
                testResults.passed
                  ? "bg-green-950 border-green-700"
                  : "bg-red-950 border-red-700"
              }`}
            >
              <h2
                className={`text-xs font-semibold uppercase tracking-wider mb-3 ${
                  testResults.passed ? "text-green-400" : "text-red-400"
                }`}
              >
                {testResults.passed ? "✅ Tests Passed" : "❌ Tests Failed"}
              </h2>
              <p
                className={`text-sm mb-3 ${
                  testResults.passed ? "text-green-200" : "text-red-200"
                }`}
              >
                {testResults.summary}
              </p>
              <div className="flex flex-wrap gap-4 text-xs mb-3">
                {testResults.coveragePercent !== null && (
                  <span
                    className={`px-2 py-1 rounded font-mono ${
                      testResults.coveragePercent >= 80
                        ? "bg-green-900 text-green-300"
                        : testResults.coveragePercent >= 70
                        ? "bg-yellow-900 text-yellow-300"
                        : "bg-red-900 text-red-300"
                    }`}
                  >
                    Coverage: {testResults.coveragePercent}%
                  </span>
                )}
                {testResults.failedTests.length > 0 && (
                  <span className="px-2 py-1 bg-red-900 text-red-300 rounded font-mono">
                    Failed: {testResults.failedTests.length}
                  </span>
                )}
              </div>
              {testResults.failedTests.length > 0 && (
                <div>
                  <p className="text-xs text-red-400 font-semibold mb-1">Failed tests:</p>
                  <ul className="list-disc list-inside space-y-0.5">
                    {testResults.failedTests.map((testName, index) => (
                      <li key={index} className="text-xs text-red-300 font-mono">
                        {testName}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </section>
          )}

          {/* ── File Explorer ── */}
          {(codeChanges.length > 0 || phase !== "idle") && (
            <FileExplorer 
              files={sampleFileStructure}
              onFileSelect={handleFileSelect}
              selectedFile={selectedFile ?? undefined}
            />
          )}

          {/* ── Live Log Stream ── */}
          {logs.length > 0 && (
            <div className="bg-gray-900 border border-gray-700 rounded-lg overflow-hidden">
              <div className="px-4 py-2 border-b border-gray-700">
                <div className="flex items-center justify-between">
                  <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                    📝 Agent Logs
                  </h2>
                  <span className="text-xs text-gray-500">{logs.length} entries</span>
                </div>
              </div>
              <div className="max-h-64 overflow-y-auto">
                <LogStream entries={[...logs]} />
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── File Preview Section ── */}
      {selectedFile && (
        <section className="bg-gray-900 border border-gray-700 rounded-lg p-4">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                🔍 File Preview
              </h2>
              <span className="text-xs px-2 py-1 rounded bg-gray-800 text-gray-300 font-mono truncate max-w-md">
                {selectedFile}
              </span>
              {selectedDiff && (
                <span className={`text-xs px-2 py-1 rounded ${
                  selectedDiff.operation === "create"
                    ? "bg-green-900 text-green-300"
                    : selectedDiff.operation === "modify"
                    ? "bg-yellow-900 text-yellow-300"
                    : "bg-red-900 text-red-300"
                }`}>
                  {selectedDiff.operation}
                </span>
              )}
            </div>
            
            <div className="flex border border-gray-700 rounded-md overflow-hidden">
              <button
                onClick={() => setViewMode("diff")}
                className={`px-3 py-1 text-xs font-medium transition-colors ${
                  viewMode === "diff" 
                    ? "bg-blue-600 text-white" 
                    : "bg-gray-800 text-gray-400 hover:bg-gray-700"
                }`}
                disabled={!selectedDiff}
              >
                Diff View
              </button>
              <button
                onClick={() => setViewMode("code")}
                className={`px-3 py-1 text-xs font-medium transition-colors ${
                  viewMode === "code" 
                    ? "bg-blue-600 text-white" 
                    : "bg-gray-800 text-gray-400 hover:bg-gray-700"
                }`}
              >
                Code View
              </button>
            </div>
          </div>
          
          {viewMode === "diff" && selectedDiff ? (
            <CodeDiffViewer diff={selectedDiff} />
          ) : (
            <CodeEditor
              initialContent={selectedFileContent}
              language={selectedFile.split(".").pop() || "text"}
              readOnly={true}
            />
          )}
        </section>
      )}

      {/* ── Human Review Panel ── */}
      {interrupted && (
        <section className="bg-orange-950 border border-orange-700 rounded-lg p-5">
          <h2 className="text-sm font-bold text-orange-300 mb-1">
            ⏸ Approve Production Deploy
          </h2>
          <p className="text-xs text-orange-400 mb-3">
            Tests passed. Approve to merge the PR and deploy to production.
          </p>
          <p className="text-sm text-orange-200 mb-4">{interruptMessage}</p>
          <div className="flex flex-wrap gap-3 mb-4">
            {prUrl && (
              <a
                href={prUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-blue-400 underline inline-flex items-center gap-1"
              >
                <span>View PR</span>
                {prNumber && <span className="font-mono">#{prNumber}</span>}
                <span>↗</span>
              </a>
            )}
            {(testResults?.stagingUrl ?? stagingUrl) && (
              <a
                href={(testResults?.stagingUrl ?? stagingUrl)!}
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-teal-400 underline inline-flex items-center gap-1"
              >
                <span>View Staging ↗</span>
              </a>
            )}
            {testResults != null && testResults.coveragePercent != null && (
              <span className="text-xs px-2 py-1 bg-green-900 text-green-300 rounded font-mono">
                Coverage: {testResults.coveragePercent}%
              </span>
            )}
          </div>
          {testResults && (
            <div className="mb-4 p-3 bg-green-900/20 border border-green-700 rounded">
              <p className="text-xs text-green-300 font-semibold mb-1">Test Summary:</p>
              <p className="text-sm text-green-200">{testResults.summary}</p>
              {testResults.failedTests.length === 0 && (
                <p className="text-xs text-green-400 mt-1">✓ All tests passed successfully</p>
              )}
            </div>
          )}
          <div className="flex gap-3">
            <button
              onClick={() => handleResume(true)}
              className="flex-1 px-5 py-3 bg-green-700 hover:bg-green-600 text-white text-sm font-semibold rounded-md transition-colors flex items-center justify-center gap-2"
            >
              <span className="text-lg">✅</span>
              <span>Approve & Deploy to Production</span>
            </button>
            <button
              onClick={() => handleResume(false)}
              className="flex-1 px-5 py-3 bg-red-700 hover:bg-red-600 text-white text-sm font-semibold rounded-md transition-colors flex items-center justify-center gap-2"
            >
              <span className="text-lg">❌</span>
              <span>Reject (Rework)</span>
            </button>
          </div>
        </section>
      )}
    </div>
  );
}